import { FEATURE, JOB_TYPE, PROJECT_NAME, type project } from './types';

export const projects: project[] = [
	{
		name: PROJECT_NAME.HELLO_WORLD,
		requirements: 'A page that says Hello World, at your domain.',
		feature: FEATURE.CORE_WEBSITE,
		costs: {
			product: 0,
			engineering: 5,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 5,
			performance: 5,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ACCOUNT_CREATION,
		requirements: 'Allow users to create accounts with email and password.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 10,
			engineering: 15,
			design: 5,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 5,
			functionality: 15,
			attractiveness: 0,
			security: 25,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BASIC_BLOG_POST,
		requirements:
			'Enable users to create, edit, and publish basic text blog posts.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 15,
			engineering: 20,
			design: 10,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 10,
			functionality: 30,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.RICH_TEXT_EDITOR,
		requirements:
			'Upgrade the blog editor with formatting options, links, and basic styling.',
		feature: FEATURE.USER_EXPERIENCE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 10,
			engineering: 25,
			design: 15,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 35,
			functionality: 5,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BLOG_CATEGORIES,
		requirements:
			'Add support for categorizing posts and filtering by category.',
		feature: FEATURE.USER_EXPERIENCE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 8,
			engineering: 12,
			design: 8,
			growth: 5,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 25,
			functionality: 15,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.COMMENT_SYSTEM,
		requirements:
			'Allow readers to comment on blog posts with basic moderation tools.',
		feature: FEATURE.SOCIAL,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST, PROJECT_NAME.ACCOUNT_CREATION],
		costs: {
			product: 15,
			engineering: 25,
			design: 10,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 25,
			attractiveness: 15,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.IMAGE_GALLERY,
		requirements:
			'Support for uploading, storing, and displaying images in blog posts.',
		feature: FEATURE.MEDIA,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 10,
			engineering: 30,
			design: 20,
			growth: 5,
		},
		scores: {
			reliability: 0,
			performance: -10,
			easeOfUse: 0,
			functionality: 20,
			attractiveness: 30,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SEO_OPTIMIZATION,
		requirements:
			'Implement SEO best practices, meta tags, and sitemap generation.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 15,
			engineering: 20,
			design: 5,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 40,
		},
	},
	{
		name: PROJECT_NAME.NEWSLETTER,
		requirements:
			'Add email newsletter subscription and automated post digests.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 15,
			engineering: 25,
			design: 10,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 20,
			attractiveness: 0,
			security: 0,
			virality: 20,
		},
	},
	{
		name: PROJECT_NAME.PREMIUM_CONTENT,
		requirements:
			'Enable premium/members-only blog posts with preview functionality.',
		feature: FEATURE.MONETIZATION,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST, PROJECT_NAME.ACCOUNT_CREATION],
		costs: {
			product: 25,
			engineering: 35,
			design: 15,
			growth: 20,
		},
		weekly_revenue_per_user: 5,
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: -10,
			functionality: 35,
			attractiveness: 0,
			security: 15,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SPAM_PROTECTION,
		requirements:
			'Implement spam prevention for comments and user registrations.',
		feature: FEATURE.SECURITY,
		dependencies: [PROJECT_NAME.COMMENT_SYSTEM],
		costs: {
			product: 10,
			engineering: 30,
			design: 5,
			growth: 5,
		},
		scores: {
			reliability: 0,
			performance: -5,
			easeOfUse: -10,
			functionality: 0,
			attractiveness: 0,
			security: 40,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ANTI_BOT_SYSTEM,
		requirements:
			'Advanced bot detection and prevention system with CAPTCHA, rate limiting, and behavior analysis.',
		feature: FEATURE.SECURITY,
		dependencies: [PROJECT_NAME.ACCOUNT_CREATION],
		costs: {
			product: 15,
			engineering: 35,
			design: 10,
			growth: 5,
		},
		scores: {
			reliability: 10,
			performance: -10,
			easeOfUse: -15,
			functionality: 0,
			attractiveness: 0,
			security: 45,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.MEDIA_SCANNING,
		requirements:
			'Implement antivirus and malware scanning for all uploaded images and media files.',
		feature: FEATURE.SECURITY,
		dependencies: [PROJECT_NAME.IMAGE_GALLERY],
		costs: {
			product: 10,
			engineering: 25,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 5,
			performance: -15,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 35,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.DDOS_PROTECTION,
		requirements:
			'Advanced DDoS protection system with traffic analysis and automatic mitigation.',
		feature: FEATURE.SECURITY,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 5,
			engineering: 40,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 30,
			performance: -5,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 50,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BRUTE_FORCE_PROTECTION,
		requirements:
			'Implement advanced protection against brute force attacks with IP blocking and account lockouts.',
		feature: FEATURE.SECURITY,
		dependencies: [PROJECT_NAME.ACCOUNT_CREATION],
		costs: {
			product: 10,
			engineering: 20,
			design: 5,
			growth: 0,
		},
		scores: {
			reliability: 5,
			performance: 0,
			easeOfUse: -5,
			functionality: 0,
			attractiveness: 0,
			security: 30,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ANALYTICS_DASHBOARD,
		requirements:
			'Add analytics tracking and dashboard for post performance and user engagement.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 20,
			engineering: 30,
			design: 25,
			growth: 15,
		},
		scores: {
			reliability: 0,
			performance: -5,
			easeOfUse: 0,
			functionality: 35,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SOCIAL_SHARING,
		requirements:
			'Add social media sharing buttons and optimized post previews for social platforms.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 10,
			engineering: 15,
			design: 20,
			growth: 15,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 10,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 30,
		},
	},
	{
		name: PROJECT_NAME.RSS_FEED,
		requirements:
			'Implement RSS feeds for posts and categories with auto-discovery.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 5,
			engineering: 15,
			design: 5,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 20,
			attractiveness: 0,
			security: 0,
			virality: 10,
		},
	},
	{
		name: PROJECT_NAME.CROSS_POSTING,
		requirements:
			'Enable automatic cross-posting to Medium, Dev.to, and other platforms.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 15,
			engineering: 25,
			design: 5,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 15,
			attractiveness: 0,
			security: 0,
			virality: 35,
		},
	},
	{
		name: PROJECT_NAME.CONTENT_SCHEDULING,
		requirements: 'Add ability to schedule posts and manage content calendar.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 20,
			engineering: 20,
			design: 15,
			growth: 10,
		},
		scores: {
			reliability: 15,
			performance: 0,
			easeOfUse: 25,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.AUTHOR_COLLABORATION,
		requirements:
			'Support multiple authors with roles, drafts sharing, and review workflow.',
		feature: FEATURE.SOCIAL,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST, PROJECT_NAME.ACCOUNT_CREATION],
		costs: {
			product: 25,
			engineering: 30,
			design: 15,
			growth: 15,
		},
		scores: {
			reliability: 10,
			performance: 0,
			easeOfUse: 0,
			functionality: 35,
			attractiveness: 0,
			security: 15,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.READING_TIME,
		requirements: 'Display estimated reading time and progress bar for posts.',
		feature: FEATURE.USER_EXPERIENCE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 5,
			engineering: 10,
			design: 15,
			growth: 5,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 25,
			functionality: 0,
			attractiveness: 15,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.RELATED_POSTS,
		requirements:
			'Show related posts based on categories, tags, and content similarity.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST, PROJECT_NAME.BLOG_CATEGORIES],
		costs: {
			product: 15,
			engineering: 25,
			design: 10,
			growth: 15,
		},
		scores: {
			reliability: 0,
			performance: -5,
			easeOfUse: 20,
			functionality: 0,
			attractiveness: 25,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.TAG_SYSTEM,
		requirements:
			'Implement detailed tagging system with tag clouds and related content.',
		feature: FEATURE.USER_EXPERIENCE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 10,
			engineering: 20,
			design: 15,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 30,
			functionality: 10,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SERIES_POSTS,
		requirements:
			'Enable creating post series with navigation and progress tracking.',
		feature: FEATURE.USER_EXPERIENCE,
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 15,
			engineering: 20,
			design: 15,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 20,
			functionality: 15,
			attractiveness: 25,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.EMAIL_DIGESTS,
		requirements:
			'Automated email digests with popular posts and personalized recommendations.',
		feature: FEATURE.ENGAGEMENT,
		dependencies: [PROJECT_NAME.NEWSLETTER, PROJECT_NAME.ANALYTICS_DASHBOARD],
		costs: {
			product: 20,
			engineering: 25,
			design: 15,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 20,
			attractiveness: 0,
			security: 0,
			virality: 30,
		},
	},
	{
		name: PROJECT_NAME.NEWSPAPER_ADS,
		requirements:
			'Run ongoing newspaper advertising campaigns to reach new readers.',
		feature: FEATURE.ENGAGEMENT,
		is_continuous: true,
		weekly_costs: {
			money: 500,
		},
		required_roles: {
			[JOB_TYPE.GROWTH]: 1,
			[JOB_TYPE.DESIGN]: 1,
		},
		target_score: 'virality',
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 5,
			engineering: 0,
			design: 15,
			growth: 20,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SOCIAL_MEDIA_MANAGEMENT,
		requirements: 'Maintain active social media presence across platforms.',
		feature: FEATURE.ENGAGEMENT,
		is_continuous: true,
		required_roles: {
			[JOB_TYPE.GROWTH]: 1,
		},
		target_score: 'virality',
		dependencies: [PROJECT_NAME.SOCIAL_SHARING],
		costs: {
			product: 5,
			engineering: 0,
			design: 10,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.CONTENT_MARKETING,
		requirements:
			'Create and distribute content across various channels to attract readers.',
		feature: FEATURE.ENGAGEMENT,
		is_continuous: true,
		required_roles: {
			[JOB_TYPE.GROWTH]: 2,
			[JOB_TYPE.DESIGN]: 1,
		},
		target_score: 'attractiveness',
		dependencies: [PROJECT_NAME.BASIC_BLOG_POST],
		costs: {
			product: 10,
			engineering: 0,
			design: 20,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.COMMUNITY_MANAGEMENT,
		requirements:
			'Actively manage and grow the blog community through engagement and moderation.',
		feature: FEATURE.SOCIAL,
		is_continuous: true,
		required_roles: {
			[JOB_TYPE.GROWTH]: 1,
			[JOB_TYPE.PRODUCT]: 1,
		},
		target_score: 'attractiveness',
		dependencies: [PROJECT_NAME.COMMENT_SYSTEM],
		costs: {
			product: 20,
			engineering: 0,
			design: 5,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SEO_MAINTENANCE,
		requirements:
			'Continuously optimize content and structure for search engines.',
		feature: FEATURE.ENGAGEMENT,
		is_continuous: true,
		required_roles: {
			[JOB_TYPE.GROWTH]: 1,
			[JOB_TYPE.ENGINEERING]: 1,
		},
		target_score: 'functionality',
		dependencies: [PROJECT_NAME.SEO_OPTIMIZATION],
		costs: {
			product: 10,
			engineering: 20,
			design: 0,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BASIC_BUG_FIXES,
		requirements: 'Fix common bugs and implement basic error tracking.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 5,
			engineering: 15,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 15,
			performance: 10,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ADVANCED_BUG_FIXES,
		requirements: 'Implement automated testing and fix edge case bugs.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.BASIC_BUG_FIXES],
		costs: {
			product: 10,
			engineering: 25,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 25,
			performance: 15,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 5,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.CRITICAL_BUG_FIXES,
		requirements: 'Implement advanced monitoring and fix critical system bugs.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.ADVANCED_BUG_FIXES],
		costs: {
			product: 15,
			engineering: 35,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 40,
			performance: 20,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 10,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SERVER_UPGRADE_T1,
		requirements: 'Upgrade to better servers with basic load balancing.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 5,
			engineering: 20,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 10,
			performance: 25,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SERVER_UPGRADE_T2,
		requirements: 'Implement advanced load balancing and CDN integration.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.SERVER_UPGRADE_T1],
		costs: {
			product: 10,
			engineering: 30,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 20,
			performance: 40,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 5,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SERVER_UPGRADE_T3,
		requirements:
			'Deploy globally distributed infrastructure with automatic scaling.',
		feature: FEATURE.CORE_WEBSITE,
		dependencies: [PROJECT_NAME.SERVER_UPGRADE_T2],
		costs: {
			product: 15,
			engineering: 45,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 35,
			performance: 60,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 10,
			virality: 0,
		},
	},
];
