import { FEATURE, JOB_TYPE, PROJECT_NAME, type project } from './types';

export const projects: project[] = [
	// Phase 1: Core Website Setup
	{
		name: PROJECT_NAME.HELLO_WORLD,
		requirements: 'A page that says Hello World, at your domain.',
		feature: FEATURE.CORE,
		costs: {
			product: 0,
			engineering: 5,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 10,
			performance: 10,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.PROFILE_CREATION,
		requirements:
			'Users can create a profile with their name, contact info, and age.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 25,
			engineering: 20,
			design: 10,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 15,
			functionality: 35,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.PROFILE_PICTURES,
		requirements:
			'Users can upload a photo to their profile. Warning: Will require more server resources and moderation!',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 20,
			engineering: 45,
			design: 15,
			growth: 0,
		},
		scores: {
			reliability: -15,
			performance: -15,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 60,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.INTERESTS,
		requirements:
			'Users can enter what they like and have those interests on their profile.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 35,
			engineering: 50,
			design: 35,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 20,
			functionality: 40,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.LOOKING_FOR,
		requirements:
			'Users can specify what kind of relationship they want and what they seek in a partner.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 40,
			engineering: 30,
			design: 20,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 25,
			functionality: 45,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ANONYMOUS_SHARING,
		requirements:
			'Users can share their profile anonymously, showing only interests and preferences until they choose to reveal more.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 30,
			engineering: 45,
			design: 25,
			growth: 20,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 30,
			attractiveness: 0,
			security: 0,
			virality: 15,
		},
	},
	{
		name: PROJECT_NAME.NEW_USER_ONBOARDING,
		requirements:
			'New users get a guided onboarding experience to help them get started.',
		feature: FEATURE.UX,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 100,
			engineering: 40,
			design: 80,
			growth: 20,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 60,
			functionality: 0,
			attractiveness: 20,
			security: 0,
			virality: 0,
		},
	},

	// Phase 2: Core Matching Features
	{
		name: PROJECT_NAME.BROWSE,
		requirements:
			'Users can browse through other profiles and see their information.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 25,
			engineering: 30,
			design: 35,
			growth: 10,
		},
		scores: {
			reliability: 0,
			performance: -10,
			easeOfUse: 0,
			functionality: 45,
			attractiveness: 0,
			security: 0,
			virality: 25,
		},
	},
	{
		name: PROJECT_NAME.HEARTING,
		requirements: 'Users can Heart other profiles to show interest.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.BROWSE],
		costs: {
			product: 20,
			engineering: 25,
			design: 30,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 40,
			attractiveness: 0,
			security: 0,
			virality: 35,
		},
	},
	{
		name: PROJECT_NAME.LOVE_FINDER_V1,
		requirements:
			'Basic matching algorithm suggests profiles based on age and location.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.BROWSE, PROJECT_NAME.GEO_LOCATION],
		costs: {
			product: 60,
			engineering: 80,
			design: 30,
			growth: 20,
		},
		scores: {
			reliability: 0,
			performance: -15,
			easeOfUse: 0,
			functionality: 60,
			attractiveness: 40,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.LOVE_CALCULATOR,
		requirements:
			'Scientific* algorithm calculates love compatibility percentage between users! (*not actually scientific)',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.INTERESTS],
		costs: {
			product: 55,
			engineering: 60,
			design: 45,
			growth: 40,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 45,
			attractiveness: 55,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.COMPATIBILITY_HOROSCOPE,
		requirements:
			'Daily horoscope readings tell users their most compatible matches. The stars never lie!',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 50,
			engineering: 45,
			design: 55,
			growth: 45,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 40,
			attractiveness: 50,
			security: 0,
			virality: 35,
		},
	},
	{
		name: PROJECT_NAME.GEO_LOCATION,
		requirements: 'Users can see profiles near them.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 15,
			engineering: 25,
			design: 5,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: -10,
			easeOfUse: 0,
			functionality: 35,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},

	// Phase 3: Communication & Engagement
	{
		name: PROJECT_NAME.PRIVATE_MESSAGING,
		requirements:
			'Users can send private messages to each other once they both show interest.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.HEARTING],
		costs: {
			product: 50,
			engineering: 70,
			design: 40,
			growth: 20,
		},
		scores: {
			reliability: -15,
			performance: -20,
			easeOfUse: 0,
			functionality: 70,
			security: 0,
			attractiveness: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.PROFILE_POSTS,
		requirements:
			'Users can post updates to their profile about their life and interests.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 40,
			engineering: 50,
			design: 35,
			growth: 25,
		},
		scores: {
			reliability: 0,
			performance: -15,
			easeOfUse: 0,
			functionality: 45,
			attractiveness: 0,
			security: 0,
			virality: 35,
		},
	},
	{
		name: PROJECT_NAME.COMMENTING,
		requirements:
			'Users can comment on profile posts, creating more engagement.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_POSTS],
		costs: {
			product: 30,
			engineering: 45,
			design: 30,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: -15,
			easeOfUse: 0,
			functionality: 40,
			attractiveness: 0,
			security: 0,
			virality: 45,
		},
	},
	{
		name: PROJECT_NAME.BLOCKING,
		requirements:
			'Users can block unwanted attention and report inappropriate behavior.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PRIVATE_MESSAGING],
		costs: {
			product: 35,
			engineering: 50,
			design: 20,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 25,
			attractiveness: 0,
			security: 60,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.RELATIONSHIP_ADVICE,
		requirements:
			'Add a section with dating tips and relationship advice from "experts".',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 70,
			engineering: 30,
			design: 40,
			growth: 50,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 30,
			attractiveness: 40,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.FIRST_DATE_PLANNER,
		requirements:
			'Interactive tool helps users plan the perfect first date based on shared interests and location.',
		feature: FEATURE.UX,
		dependencies: [PROJECT_NAME.INTERESTS, PROJECT_NAME.GEO_LOCATION],
		costs: {
			product: 80,
			engineering: 75,
			design: 85,
			growth: 40,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 30,
			functionality: 50,
			attractiveness: 60,
			security: 0,
			virality: 0,
		},
	},

	// Phase 4: Infrastructure & Scaling
	{
		name: PROJECT_NAME.ADVANCED_BUG_FIXES_1,
		requirements:
			'Implement automated testing and monitoring to improve reliability.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.BASIC_BUG_FIXES_1],
		costs: {
			product: 20,
			engineering: 80,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 45,
			performance: 25,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BASIC_BUG_FIXES_1,
		requirements: 'Fix common bugs.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 5,
			engineering: 25,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 25,
			performance: 20,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.IMPROVED_SERVERS_1,
		requirements: 'Upgrade servers to handle increased load.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.ADVANCED_BUG_FIXES_1],
		costs: {
			product: 5,
			engineering: 45,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 50,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},

	// Phase 5: Monetization
	{
		name: PROJECT_NAME.BANNER_ADS,
		requirements: 'Put ads on your site to collect revenue.',
		feature: FEATURE.MONETIZATION,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 25,
			engineering: 45,
			design: 35,
			growth: 80,
		},
		scores: {
			reliability: 0,
			performance: -25,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: -35,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SUPER_HEART,
		requirements:
			'Users can pay to SuperHeart someone on your website, boosting their visibility above those who receive a regular Heart.',
		feature: FEATURE.MONETIZATION,
		dependencies: [PROJECT_NAME.HEARTING],
		costs: {
			product: 20,
			engineering: 10,
			design: 30,
			growth: 40,
		},
		weekly_revenue_per_user: 1,
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 25,
			attractiveness: 35,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.AD_FREE,
		requirements: 'Allow users to pay to never see ads.',
		feature: FEATURE.MONETIZATION,
		dependencies: [PROJECT_NAME.BANNER_ADS],
		costs: {
			product: 20,
			engineering: 40,
			design: 40,
			growth: 100,
		},
		weekly_revenue_per_user: 2,
		scores: {
			reliability: 0,
			performance: 45,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 55,
			security: 0,
			virality: 0,
		},
	},

	// Phase 6: Advanced Features & Optimization
	{
		name: PROJECT_NAME.LOVE_FINDER_V2,
		requirements:
			'Using more information that users provide, match users with higher confidence.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.LOVE_FINDER_V1],
		costs: {
			product: 120,
			engineering: 140,
			design: 80,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: -20,
			easeOfUse: 0,
			functionality: 80,
			attractiveness: 60,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BASIC_BUG_FIXES_2,
		requirements: 'Fix increasingly complex bugs as the system grows.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.IMPROVED_SERVERS_1],
		costs: {
			product: 25,
			engineering: 130,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 60,
			performance: 40,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ADVANCED_BUG_FIXES_2,
		requirements: 'Implement more sophisticated testing and monitoring.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.BASIC_BUG_FIXES_2],
		costs: {
			product: 40,
			engineering: 170,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 80,
			performance: 40,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.IMPROVED_SERVERS_2,
		requirements: 'Further upgrade servers for better performance.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.ADVANCED_BUG_FIXES_2],
		costs: {
			product: 30,
			engineering: 250,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 40,
			performance: 120,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.LOVE_FINDER_V3,
		requirements:
			'Using more information, improve the confidence of matches. Also tweaks the Browse page to be automatically sorted by confidence.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.LOVE_FINDER_V2],
		costs: {
			product: 200,
			engineering: 300,
			design: 160,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: -20,
			easeOfUse: 0,
			functionality: 80,
			attractiveness: 120,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.BASIC_BUG_FIXES_3,
		requirements: 'Fix critical bugs in the complex system.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.IMPROVED_SERVERS_2],
		costs: {
			product: 50,
			engineering: 300,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 100,
			performance: 100,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ADVANCED_BUG_FIXES_3,
		requirements:
			'Implement advanced system monitoring and automated recovery.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.BASIC_BUG_FIXES_3],
		costs: {
			product: 70,
			engineering: 400,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 120,
			performance: 180,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.IMPROVED_SERVERS_3,
		requirements: 'Final server upgrades for maximum performance.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.ADVANCED_BUG_FIXES_3],
		costs: {
			product: 60,
			engineering: 600,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 200,
			performance: 200,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},

	// Add to Phase 1: Core Website Setup
	{
		name: PROJECT_NAME.BROWSER_COMPATIBILITY,
		requirements: 'Make the site work on all available browsers.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 10,
			engineering: 35,
			design: 10,
			growth: 0,
		},
		scores: {
			reliability: 20,
			performance: 15,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.DIAL_UP_OPTIMIZATION,
		requirements: 'Optimize the site to work well on slow dial-up connections.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		costs: {
			product: 35,
			engineering: 90,
			design: 20,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 45,
			easeOfUse: 25,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},

	// Add to Phase 2: Basic User Experience & Matching
	{
		name: PROJECT_NAME.PERSONALITY_QUIZ,
		requirements:
			'Users can take a detailed personality quiz to improve matching.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.INTERESTS],
		costs: {
			product: 80,
			engineering: 50,
			design: 45,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: -15,
			easeOfUse: 0,
			functionality: 50,
			attractiveness: 45,
			security: 0,
			virality: 0,
		},
	},

	// Add to Phase 3: User Engagement & Growth
	{
		name: PROJECT_NAME.CHAT_ROOMS,
		requirements: 'Create topic-based chat rooms where singles can mingle.',
		feature: FEATURE.CORE,
		dependencies: [PROJECT_NAME.PRIVATE_MESSAGING],
		costs: {
			product: 90,
			engineering: 160,
			design: 80,
			growth: 40,
		},
		scores: {
			reliability: -25,
			performance: -30,
			easeOfUse: 0,
			functionality: 70,
			attractiveness: 0,
			security: 0,
			virality: 0,
		},
	},

	// Add before Phase 4: Security & Moderation
	{
		name: PROJECT_NAME.SECURITY_IMPROVEMENTS_1,
		requirements: 'Fix security bugs and add preventative measures.',
		feature: FEATURE.BUGS,
		dependencies: [],
		costs: {
			product: 0,
			engineering: 25,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: -5,
			functionality: 0,
			attractiveness: 0,
			security: 35,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.MODERATION_TOOLS,
		requirements: 'Build tools for moderators to review profiles and content.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.PROFILE_POSTS, PROJECT_NAME.PRIVATE_MESSAGING],
		costs: {
			product: 35,
			engineering: 60,
			design: 20,
			growth: 0,
		},
		scores: {
			reliability: 20,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 50,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.SECURITY_IMPROVEMENTS_2,
		requirements: 'Implement advanced security measures to protect user data.',
		feature: FEATURE.BUGS,
		dependencies: [PROJECT_NAME.SECURITY_IMPROVEMENTS_1],
		costs: {
			product: 10,
			engineering: 70,
			design: 0,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: -10,
			functionality: 0,
			attractiveness: 0,
			security: 70,
			virality: 0,
		},
	},

	// newspaper ads
	{
		name: PROJECT_NAME.NEWSPAPER_ADS,
		requirements:
			'Launch a newspaper advertising campaign to reach potential users during their commute.',
		feature: FEATURE.MARKETING,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		weekly_costs: {
			money: 100,
		},
		costs: {
			product: 25,
			engineering: 0,
			design: 20,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 0,
			security: 0,
			virality: 30,
		},
	},

	// Add to Phase 6: Advanced Features
	{
		name: PROJECT_NAME.RADIO_ADS,
		requirements:
			'Launch a radio advertising campaign to reach potential users during their commute.',
		feature: FEATURE.MARKETING,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		weekly_costs: {
			money: 300,
		},
		costs: {
			product: 25,
			engineering: 0,
			design: 20,
			growth: 60,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 10,
			security: 0,
			virality: 50,
		},
	},
	{
		name: PROJECT_NAME.COLLEGE_CAMPUS_CAMPAIGN,
		requirements:
			'Launch a nationwide college campus campaign with student ambassadors spreading digital love!',
		feature: FEATURE.MARKETING,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		weekly_costs: {
			money: 250,
		},
		costs: {
			product: 40,
			engineering: 5,
			design: 45,
			growth: 85,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 60,
			security: 0,
			virality: 90,
		},
	},
	{
		name: PROJECT_NAME.TV_INFOMERCIAL,
		requirements:
			'Late-night TV infomercial campaign: "Tired of being lonely? The Internet has your solution!"',
		feature: FEATURE.MARKETING,
		dependencies: [PROJECT_NAME.PROFILE_CREATION],
		weekly_costs: {
			money: 500,
		},
		costs: {
			product: 30,
			engineering: 0,
			design: 50,
			growth: 150,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 0,
			functionality: 0,
			attractiveness: 40,
			security: 0,
			virality: 70,
		},
	},
	{
		name: PROJECT_NAME.BASIC_UI_IMPROVEMENTS,
		requirements:
			'Clean up the basic layout and make the site more visually appealing with consistent spacing and typography.',
		feature: FEATURE.UX,
		dependencies: [PROJECT_NAME.HELLO_WORLD],
		costs: {
			product: 30,
			engineering: 15,
			design: 50,
			growth: 0,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 25,
			functionality: 0,
			attractiveness: 30,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.USABILITY_TESTING,
		requirements:
			'Conduct user testing sessions to identify pain points and improve navigation flows.',
		feature: FEATURE.UX,
		dependencies: [PROJECT_NAME.BASIC_UI_IMPROVEMENTS],
		costs: {
			product: 70,
			engineering: 25,
			design: 80,
			growth: 30,
		},
		scores: {
			reliability: 0,
			performance: 0,
			easeOfUse: 55,
			functionality: 0,
			attractiveness: 35,
			security: 0,
			virality: 0,
		},
	},
	{
		name: PROJECT_NAME.ADVANCED_UI_OVERHAUL,
		requirements:
			'Complete redesign with modern visual elements, smooth animations, and intuitive interaction patterns.',
		feature: FEATURE.UX,
		dependencies: [PROJECT_NAME.USABILITY_TESTING],
		costs: {
			product: 120,
			engineering: 160,
			design: 160,
			growth: 40,
		},
		scores: {
			reliability: 0,
			performance: -15,
			easeOfUse: 80,
			functionality: 0,
			attractiveness: 100,
			security: 0,
			virality: 0,
		},
	},
];
